apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: devops-nginx-2
    service: webserver
  name: devops-nginx-2
spec:
  containers:
  - image: nginx
    name: devops-nginx-2
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: 256Mi
